name: medconnect
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1
  syncfusion_flutter_datepicker: ^24.2.8
  flutter_chat_widget: ^0.0.4
  flutter_chat_ui: ^1.6.13
  flutter_chat_types: ^3.6.2
  flutter_local_notifications: ^17.1.2
  firebase_core: ^2.32.0
  file_picker: ^8.0.3
  uuid: ^4.4.0
  mime: ^1.0.5
  open_filex: ^4.4.0
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  firebase_messaging: ^14.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
